name: Code Quality Check

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'silver/**.sql'
      - 'gold/**.sql'
      - 'silver/**.py'
      - 'gold/**.py'

jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- PASO NUEVO: Obtener la lista de archivos modificados ---
      - name: Get changed files
        id: changed_files  # Le damos un ID para referenciar su salida
        uses: tj-actions/changed-files@v44 # Usamos la action
        with:
          files: | # Le decimos qué archivos nos interesan
            silver/**.sql
            gold/**.sql
            silver/**.py
            gold/**.py

      # --- PASO MODIFICADO: Ejecutar el linter solo en los archivos cambiados ---
      - name: Run Unified Linter
        # Solo ejecutamos este paso si el paso anterior encontró archivos modificados
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          echo "Analizando los siguientes archivos modificados:"
          echo "${{ steps.changed_files.outputs.all_changed_files }}"
          python ci/code_linter.py ${{ steps.changed_files.outputs.all_changed_files }}